[build]
target = "thumbv7em-none-eabihf" # STM32F411CEU6 - Cortex-M4F

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-L.", # Add root dir to linker path to pick up memory.x
]

# Add `--connect-under-reset` flag if ST-LINK is wired to the STM's reset pin
runner = "probe-rs run --chip STM32F411CEUx"

[env]
DEFMT_LOG = "debug"

